{{- if ne .Values.secret.crt "" }}
apiVersion: v1
kind: Secret
metadata:
  generateName: {{ index .Values "sealed-secrets" "secretName" }}
  labels:
    app: {{ template "sealed-secrets-umbrella.name" . }}
    chart: {{ template "sealed-secrets-umbrella.chart" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    sealedsecrets.bitnami.com/sealed-secrets-key: active
{{- if ne .Values.secret.nameSuffix "" }}
    name: {{ index .Values "sealed-secrets" "secretName" }}{{ .Values.secret.nameSuffix }}
{{- end }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secret.crt | b64enc | quote }}
  tls.key: {{ .Values.secret.key | b64enc | quote }}
{{- end }}
