# Default values for sealed-secrets-httppubcert.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: djnos/k8s-sealed-secrets-httppubcert
  tag: 0.2.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  nameSuffix: ""
  annotations: {}
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

httppubcert:
  certPath: "/cert"
  listenAddress: ":{{ toString ((index .Values.httppubcert.ports 0).containerPort) }}"
  sealedSecretsNs: "kube-system"
  secretPrefix: "sealed-secrets-key"
  verbose: false
  command:
  - /k8s-sealed-secrets-httppubcert
  args:
  - "--certpath={{ .Values.httppubcert.certPath }}"
  - "--listenaddress={{ tpl .Values.httppubcert.listenAddress . }}"
  - "--sealedsecretsns={{ .Values.httppubcert.sealedSecretsNs }}"
  - "--secretprefix={{ .Values.httppubcert.secretPrefix }}"
  - "{{ if .Values.httppubcert.verbose }}--verbose{{ end }}"
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  livenessProbe:
    httpGet:
      path: "{{ .Values.httppubcert.certPath }}"
      port: http
  readinessProbe:
    httpGet:
      path: "{{ .Values.httppubcert.certPath }}"
      port: http
