kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "sealed-secrets-httppubcert.labels" . | indent 4 }}
  name: {{ include "sealed-secrets-httppubcert.fullname" . }}
subjects:
- kind: User
  name: system:serviceaccount:{{ .Release.Namespace }}:{{ include "sealed-secrets-httppubcert.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "sealed-secrets-httppubcert.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
