kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "sealed-secrets-httppubcert.labels" . | indent 4 }}
  name: {{ include "sealed-secrets-httppubcert.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
