apiVersion: v1
kind: Service
metadata:
  name: {{ template "sealed-secrets-httppubcert.fullnameSuffix" (dict "scope" $ "suffix" .Values.service.nameSuffix) }}
  labels:
{{ include "sealed-secrets-httppubcert.labels" . | indent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .annotations | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  type: {{ .Values.service.type }}
  sessionAffinity: None
  {{- if hasKey .Values.service "externalIPs" }}
  externalIPs:
  {{- toYaml .Values.service.externalIPs | indent 4 }}
  {{- end }}
  {{- if hasKey .Values.service "loadBalancerIP" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sealed-secrets-httppubcert.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
