dependencies:
- name: sealed-secrets
  version: ^1.9.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: sealed-secrets.enabled
- name: sealed-secrets-httppubcert
  #repository: "file://../sealed-secrets-httppubcert/sealed-secrets-httppubcert"
  condition: sealed-secrets-httppubcert.enabled
